version: '2'
services:
  well-service:
    container_name: well-service
    build:
      context: .
      dockerfile: Dockerfile
    image: oil-station:latest
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge